### PR TITLE
add slack and minecraft controllers

### PR DESCRIPTION
**Pull request by sformichella**
- add controllers folder
- add slack-bots and minecraft-bots controllers
- add routing to controllers from app.js

### CODE REVIEW

**Review by RSakultarawattn — DISMISSED** [review]
looks good

**Review by DonnyLVu — CHANGES_REQUESTED** [review]
minecraft-thing needs to be edited

**Review by ryanleviathan — DISMISSED** [review]

**Review by RSakultarawattn — CHANGES_REQUESTED** [review]
remove minecraft_thing.pem

**Review by DonnyLVu — APPROVED** [review]
Good fix

**Review by RSakultarawattn — APPROVED** [review]
NOW it looks good

**Pull request merged**
